<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="src\Layouts\" />
    <Folder Include="src\Data\" />
    <Folder Include="src\Feedback\" />
    <Folder Include="src\Forms\" />
    <Folder Include="wwwroot\css\" />
  </ItemGroup>

</Project>
